#!/bin/sh
#iptables -I INPUT -p tcp --dport 6800 -j ACCEPT
#iptables -I INPUT -p udp --dport 6800 -j ACCEPT
#/jffs/bin/aria restart /mnt/sda1/Downloads

start_aria()
{
	SDIR=$(cd "${0%/*}"; pwd)
	if [ ! -z "$1" ]; then
		CDIR="$1"
	else
		CDIR=$(pwd)
	fi
	TASK=$CDIR/aria.task
	if [ ! -r $TASK ]; then touch $TASK; fi
	XOPT='--split=10 --max-connection-per-server=10 --timeout=1 --max-tries=0 --user-agent=netdisk;6.0.0.12;PC;PC-Windows;10.0.16299;WindowsBaiduYunGuanJia'
	$SDIR/aria2c -D -d $CDIR -c -i $TASK --save-session=$TASK --enable-rpc --rpc-listen-all --rpc-allow-origin-all --file-allocation=falloc --disable-ipv6 $XOPT
}

case "$1" in
	start)
		echo "Starting aria2c daemon..."
		start_aria $2
		;;
	stop)
		echo "Shutting down aria2c daemon..."
		killall aria2c
		;;
	restart)
		$0 stop
		sleep 1
		$0 start $2
		;;
	*)
		start_aria $1
		;;
esac
