[global]
# General
netbios name = Store
server string = Storage
#interfaces = lo br0
#bind interfaces only = yes

# Account
passdb backend = smbpasswd
map to guest = Bad User
access based share enum = yes

# Content
force create mode = 0644
force directory mode = 0755
load printers = no
disable spoolss = yes

# Connection
deadtime = 30
min receivefile size = 16384
write cache size = 524288
socket options = TCP_NODELAY IPTOS_LOWDELAY
aio read size = 16384
aio write size = 16384
use sendfile = yes
#min protocol = SMB2
#max protocol = SMB3
#max connections = 100

# Mac OS
#mdns name = mdns
delete veto files = yes
veto files = /Thumbs.db/.DS_Store/._.DS_Store/.apdisk/
vfs objects = fruit
fruit:model = Xserve
fruit:copyfile = yes

[Documents]
path = /media/STORE/Documents
public = no
writable = yes
valid users = admin

[Downloads]
path = /media/STORE/Downloads
public = yes
writable = yes

[Movies]
path = /media/STORE/Movies
public = yes
write list = admin

[Music]
path = /media/STORE/Music
public = yes
write list = admin

[Pictures]
path = /media/STORE/Pictures
public = yes
write list = admin

[Public]
path = /media/STORE/Public
public = yes
write list = admin
